### ISSUE TITLE
Support interrupts instead of timeouts

### ISSUE THREAD

**Issue by mh00h** [adafruit/Adafruit_CircuitPython_RFM9x#29]
It is difficult to use this library with bidirectional communication. read_lora_data(timeout=5s) loops are currently required to check if there is new data to transmit. If interrupts could be supported, we wouldn't need to stop listening for data ever except when there is data to transmit. I think this is even [referenced in the code](https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/blob/master/adafruit_rfm9x.py#L682); perhaps now would be a better time for adafruit to consider it?

**Comment by ladyada** [comment]
correct, we do not support interrupts in circuitpython! you can check out this thread for more info - closing this issue
https://github.com/adafruit/circuitpython/issues/1380
