### ISSUE TITLE
Unclear about size of _BUFFER

### ISSUE THREAD

**Issue by reyeslucero** [adafruit/Adafruit_CircuitPython_RFM9x#37]
I am confused about the initialization of the global buffer for the radio _BUFFER. 
It should be 256 bytes which is the size specified in the radio's data sheet. 
However, it seems at though its only being initialized to 10 bytes? 
Here is the code for initialization:

    # Global buffer to hold data sent and received with the chip.  This must be
    # at least as large as the FIFO on the chip (256 bytes)!  Keep this on the
    # class level to ensure only one copy ever exists (with the trade-off that
    # this is NOT re-entrant or thread safe code by design).
    _BUFFER = bytearray(10)  

If someone could provide insight into the behavior of _BUFFER, that would be greatly appreciated.

**Comment by jerryneedell** [comment]
Take a look at lines 401 to 437 in adafruit_rfm9x.py.
You’ll see that BUFFER is only used to hold the SPI command or to receive read one byte.

The comment describing. BUFFER is incorrect and should be updated.

**Comment by brentru** [comment]
@jerryneedell  possibly changing `_BUFFER` to `CMD_BUFFER` would make this more clear?

**Comment by jerryneedell** [comment]
address by #42  -- the name is still _BUFFER, but the comment was changed to clarify its use.

**Comment by jerryneedell** [comment]
addressed in #42
