### ISSUE TITLE
Receiving all zeroes eventually

### ISSUE THREAD

**Issue by tahnok** [adafruit/Adafruit_CircuitPython_RFM9x#43]
Hello!

I am running into an issue where after successfully receiving for a while, eventually I receive all 0s, on any call to `receive`

I tried calling the `reset` method when this occurs, but it persists anyway. The only solution I've found is to restart the little script I have (which indicts it's not a transmit problem)

Program here: https://gist.github.com/tahnok/dad135976baead3b38fb074ff500dfa6

I can try and debug, but I'm not really sure how to get more useful information...

**Comment by jerryneedell** [comment]
How long is “a while”?
Is this on a Raspberry Pi?
What rfm9x board are you using?
How large is the packet of all zeros?

**Comment by tahnok** [comment]
> How long is “a while”?
unclear, at least 15 minutes?
> Is this on a Raspberry Pi?
Yep, rpi 2
> What rfm9x board are you using?
rfm95w, from aliexpress
> How large is the packet of all zeros?
Not sure, I'll grab that next time it goes 💥

**Comment by tahnok** [comment]
It's returning `bytearray(b'\x00\x00\x00\x00\x00\x00\x00')` (8 bytes)

**Comment by jerryneedell** [comment]
Shouldn’t there be some indentation here?
https://gist.github.com/tahnok/dad135976baead3b38fb074ff500dfa6#file-bastion-py-L6
It is not clear how you are handling a None response.

**Comment by tahnok** [comment]
Must have messed up creating the gist, sorry about that

https://gist.github.com/tahnok/4b5c88106a61da452ae948bf6dd82a68

Interestingly, it has been running all night with the transmitter off and this issue hasn't cropped up

**Comment by jerryneedell** [comment]
What is the Transmitter?

**Comment by tahnok** [comment]
A SAMD21 board I made, and my own hand rolled driver for the rfm9x, so it's possible I'm transmitting some garbage accidentally?

https://github.com/tahnok/hummingbird_atmel_studio/blob/master/Hummingbird/rfm9x.c

**Comment by jerryneedell** [comment]
i get a "404" error on that link.
I have not been able to reproduce this issue.  I'll run a "listener" on my Raspberry Pi for a few days and see if it does anything similar.
i do see many random packets of "stuff" but so far, not repeated sets of 0x00 s

**Comment by tahnok** [comment]
Whoops, I didn't realize that was a private repo, it's public now

**Comment by jerryneedell** [comment]
I just ran my Raspberry Pi overnight just listening and did not see any packets of 0x00's.
I'm not sure how to help track this down without more information to go on.

**Comment by tahnok** [comment]
Ok, thanks for investigating! I'll see if I can reproduce on different hardware or with a different cable steup
