### ISSUE TITLE
No RH Mesh adaptation

### ISSUE THREAD

**Issue by bzoss** [adafruit/Adafruit_CircuitPython_RFM9x#50]
The current adaptation of the RadioHead library is the minimum implementation.  Is there a plan to incorporate more advanced features - such as the Mesh Networking capability?

**Comment by brentru** [comment]
There are no current plans to incorporate RH Mesh Networking. Advanced RH features in this library, such as reliable datagram mode (prev. added), are contributed as pull requests.  I'd love to see a Mesh Networking PR for this library if you're up to it.

**Comment by bzoss** [comment]
Maybe I'll give it a go.  It's just converting the C over, but I'm less fluent in C....

**Comment by jerryneedell** [comment]
Since the has been no follow-up on this, I'll close it. Please re-open if needed.
