### ISSUE TITLE
Receive packets in the form of char string

### ISSUE THREAD

**Issue by TinManAkshay** [adafruit/Adafruit_CircuitPython_RFM9x#54]
Hi all,

So far rfm9x.receive() function can receive the packets in the form of bytes right. Can the same function receive the packets in the form of char string as well?

Thanks,
Akshay

**Comment by brentru** [comment]
It can not receive packets as char strings but you can convert them. After you called rfm9x.receive(), you would need to convert the received payload from raw bytes to character string via something like `payload_bytes.decode()`
