### ISSUE TITLE
Write function has no argument "end"

### ISSUE THREAD

**Issue by Timonzimm** [adafruit/Adafruit_CircuitPython_RFM9x#6]
Hi there, 
While trying to run the example I stumble upon a weird issue that might come from a mismatch in the dependencies/libraries. Indeed, in this file at line 421:
https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/blob/master/adafruit_rfm9x.py#L421

The "write" function doesn't seem to support an "end" argument. Have you noticed the same error before?

Best,
Timon

**Comment by caternuson** [comment]
Are you using `bitbangio`? That version of `write` does not have the `end` argument:
https://circuitpython.readthedocs.io/en/3.x/shared-bindings/bitbangio/SPI.html#bitbangio.SPI.write
while the `busio` version does:
https://circuitpython.readthedocs.io/en/3.x/shared-bindings/busio/SPI.html#busio.SPI.write

If you are using a board that lacks hardware SPI, like the ESP8266, then it will be using `bitbangio` even if the code imports `busio`. 

There is an issue for this here:
https://github.com/adafruit/circuitpython/issues/1020
so closing this one.
