### ISSUE TITLE
enable CRC by default for Arduino (Radiohead) compatibility

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_RFM9x#62]
The Arduino RadioHead library has the CRC enabled by default, but the CircuitPython library has it disabled by default. It is easily enable by setting the enable_crc property to True.
We have generally tried to make the defaults compatible with the RadioHead defaults so this should probably be changed.
Let me know if there are any objections. I  will prepare a PR for discussion.
The change may impact "cross-platform" users since they will have to make a change to remain compatible.

**Comment by brentru** [comment]
Closing via #63
